apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: scheduler
  name: scheduler
spec:
  selector:
    matchLabels:
      app: scheduler
  template:
    metadata:
      labels:
        app: scheduler
      name: scheduler
    spec:
      nodeName: master
      serviceAccountName: scheduler
      containers:
        - name: scheduler
          image: ketidevit/scheduler:v1.0
        - name: kubectl
          image: kelseyhightower/kubectl:1.3.4
          args:
            - "proxy"
